### ISSUE TITLE
Improve the definition of SACM Component Discovery

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-terminology#69]
SACM Component Discovery: "The task of brokering appropriate SACM components according to their capabilities or roles on request."

The definition doesn't seem to match the term. I would expect, instead, to see something like: "the action or process of discovering SACM Components within a SACM Domain."

**Comment by henkbirkholz** [comment]
Agreed. While the definition is not "wrong" it is totally confusing.

Interestingly, you wrote action instead of task (which is on my list and off-topic). I will go with task for now, but at some point we should revisit task.

Maybe somthing like this? "the task of discovering the capabilities provided by SACM components within a SACM domain via an appropriate set of control plane functions." This reverses the order of Component and Capability - but maybe that is for the better? Capabilities are the starting point, I think. If 10 components can provide the capability, maybe they provide also other characteristics that help me to choose.

**Comment by adammontville** [comment]
Addressed in branch `no-label-issues` (to be sync'd soon). 

Please review, Henk, because I segregated your proposal to look more like the definition followed by an expositional sentence:

`The task of discovering ...`

Followed by

` This is likely to be performed via an appropriate set of...`
